server:
  port: 8083

spring:
  application:
    name: appointment-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5434/appointmentdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092  # Kafka KRaft broker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
