server:
  port: 8083

spring:
  application:
    name: appointment-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/appointmentdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

  # ✅ Disable Kafka temporarily if it keeps failing
  # autoconfigure:
  #   exclude:
  #     - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

eureka:
  client:
    enabled: false  # ✅ Disable Eureka for local testing
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: false
    fetch-registry: false