server:
  port: 8081

spring:
  application:
    name: patient-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/patientdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jackson:
      deserialization:
        ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
      default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
