server:
  port: 8084

spring:
  application:
    name: billing-service

  datasource:
    url: jdbc:postgresql://localhost:5435/billingdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092
