server:
  port: 8085

spring:
  application:
    name: surgery-service

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/surgerydb?authSource=admin&authMechanism=SCRAM-SHA-1

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
