server:
  port: 8050

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ==========================================
        # ✅ AUTH SERVICE (JWT LOGIN & REGISTER)
        # ==========================================
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AddResponseHeader=X-Service, Auth-Service

        # ==========================================
        # ✅ PATIENT SERVICE
        # ==========================================
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/v1/patients/**, /api/v1/patient/**
          filters:
            - AddResponseHeader=X-Service, Patient-Service

        # ==========================================
        # ✅ DENTIST SERVICE
        # ==========================================
        - id: dentist-service
          uri: lb://dentist-service
          predicates:
            - Path=/api/v1/dentists/**
          filters:
            - AddResponseHeader=X-Service, Dentist-Service

        # ==========================================
        # ✅ APPOINTMENT SERVICE
        # ==========================================
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**
          filters:
            - AddResponseHeader=X-Service, Appointment-Service

        # ==========================================
        # ✅ BILLING SERVICE
        # ==========================================
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/v1/bills/**
          filters:
            - AddResponseHeader=X-Service, Billing-Service

        # ==========================================
        # ✅ SURGERY SERVICE
        # ==========================================
        - id: surgery-service
          uri: lb://surgery-service
          predicates:
            - Path=/api/v1/surgeries/**
          filters:
            - AddResponseHeader=X-Service, Surgery-Service

        # ==========================================
        # ✅ NOTIFICATION SERVICE
        # ==========================================
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AddResponseHeader=X-Service, Notification-Service

        # ==========================================
        # ✅ OFFICE MANAGER SERVICE
        # ==========================================
        - id: office-manager-service
          uri: lb://office-manager-service
          predicates:
            - Path=/api/v1/manager/**
          filters:
            - AddResponseHeader=X-Service, Office-Manager-Service

# ==========================================
# ✅ EUREKA DISCOVERY CLIENT CONFIGURATION
# ==========================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
